1. Подберите скорость обучения (alpha) и количество итераций:

In [6]:
import numpy as np
import matplotlib.pyplot as plt

In [7]:
X = np.array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
              [1, 1, 2, 1, 3, 0, 5, 10, 1, 2]])

In [8]:
y = [45, 55, 50, 59, 65, 35, 75, 80, 50, 60]

In [9]:
def calc_mse(y, y_pred):
  err = np.mean((y - y_pred)**2)
  return err

In [57]:
n = X.shape[1]
alpha = 1e-2
W = np.array([1, 0.5])
W, alpha

(array([1. , 0.5]), 0.01)

In [31]:
for i in range(1000):
  y_pred = np.dot(W, X)
  err = calc_mse(y, y_pred)
  for ii in range(W.shape[0]):
    W[ii] -= alpha * (1/n * 2 * np.sum(X[ii] * (y_pred - y)))
  if i % 100 == 0:
    print(i, W, err)

0 [2.102 3.9  ] 3173.15
100 [31.88770806  6.74418155] 175.19445858001853
200 [41.83683774  4.90699865] 61.9177717428135
300 [45.33508261  4.26102097] 47.913169919666785
400 [46.56511152  4.03388672] 46.181755648107604
500 [46.99760587  3.95402334] 45.96769776787538
600 [47.14967657  3.92594232] 45.941233404700036
700 [47.20314662  3.91606866] 45.93796156758051
800 [47.2219474   3.91259695] 45.93755706443538
900 [47.228558    3.91137626] 45.937507054979434


*2. В этом коде мы избавляемся от итераций по весам, но тут есть ошибка, исправьте ее:

In [43]:
for i in range(1000):
  y_pred = np.dot(W, X)
  err = calc_mse(y, y_pred)
  '''for ii in range(W.shape[0]):
    W[ii] -= alpha * (1/n * 2 * np.sum(X[ii] * (y_pred - y)))'''
  W -= (alpha * (1/n * 2 * np.sum(X * (y_pred - y), axis=1)))
  if i % 100 == 0:
    print(i, W, err)

0 [2.102 3.9  ] 3173.15
100 [31.88770806  6.74418155] 175.19445858001853
200 [41.83683774  4.90699865] 61.9177717428135
300 [45.33508261  4.26102097] 47.913169919666785
400 [46.56511152  4.03388672] 46.181755648107604
500 [46.99760587  3.95402334] 45.96769776787538
600 [47.14967657  3.92594232] 45.941233404700036
700 [47.20314662  3.91606866] 45.93796156758051
800 [47.2219474   3.91259695] 45.93755706443538
900 [47.228558    3.91137626] 45.937507054979434


*3: вместо того, чтобы задавать количество итераций, задайте условие остановки алгоритма - когда ошибка за итерацию
начинает изменяться ниже определенного порога (упрощенный аналог параметра tol в линейной регрессии в sklearn)

In [63]:
W = np.array([1, 0.5])
max_iter = 1000
i = 0
eps = 1e-6
# Будем хранить последние 3 ошибки
errs = [1,1,1]

while(i < max_iter):
  y_pred = np.dot(W, X)
  err = calc_mse(y, y_pred)
  errs[i%3] = err  
  W -= (alpha * (1/n * 2 * np.sum(X * (y_pred - y), axis=1)))
  if abs(np.mean(errs) - err) < eps:
    print(i, W, err)
    break
  if i % 100 == 0:
    print(i, W, err)
  i+=1  
    

0 [2.102 3.9  ] 3173.15
100 [31.88770806  6.74418155] 175.19445858001853
200 [41.83683774  4.90699865] 61.9177717428135
300 [45.33508261  4.26102097] 47.913169919666785
400 [46.56511152  4.03388672] 46.181755648107604
500 [46.99760587  3.95402334] 45.96769776787538
600 [47.14967657  3.92594232] 45.941233404700036
700 [47.20314662  3.91606866] 45.93796156758051
800 [47.2219474   3.91259695] 45.93755706443538
810 [47.22295925  3.91241011] 45.937546299739466


In [61]:
45.937547277798465 - 45.937546299739466

9.78058999123732e-07

In [33]:
X

array([[ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  2,  1,  3,  0,  5, 10,  1,  2]])

In [39]:
np.sum(X, axis=1)*2*1/10

array([2. , 5.2])

In [40]:
np.dot(W, X)

array([51.14187053, 51.14187053, 55.05284598, 51.14187053, 58.96382143,
       47.23089509, 66.78577232, 86.34064955, 51.14187053, 55.05284598])

In [44]:
np.dot(W, X)-y

array([ 6.14181862, -3.85818138,  5.05276811, -7.85818138, -6.0362824 ,
       12.23086913, -8.21438342,  6.34036402,  1.14181862, -4.94723189])

In [46]:
y_pred = np.dot(W, X)
X * (y_pred - y)

array([[  6.14181862,  -3.85818138,   5.05276811,  -7.85818138,
         -6.0362824 ,  12.23086913,  -8.21438342,   6.34036402,
          1.14181862,  -4.94723189],
       [  6.14181862,  -3.85818138,  10.10553622,  -7.85818138,
        -18.10884721,   0.        , -41.07191712,  63.40364021,
          1.14181862,  -9.89446378]])

In [48]:
errs = [1,1,1]
np.mean(errs)

1.0